import './CookiePolicy.css'; // Reuse the same styling

const PrivacyPolicy = () => {
  return (
    <div className="policy-page">
      <div className="policy-container">
        <h1>Privacy Policy</h1>
        <p className="policy-updated">Last Updated: 17 November 2025</p>

        <section className="policy-section">
          <h2>Introduction</h2>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information
            when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
            and use of information in accordance with this Privacy Policy.
          </p>
        </section>

        <section className="policy-section">
          <h2>Definitions</h2>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to FLIGHTSTORY, 73 Cornhill, London, EC3V 3QQ.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: United Kingdom</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the DOAC Perks Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to DOAC Perks, accessible from https://doac-perks.com</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>Types of Data Collected</h2>

          <h3>Personal Data</h3>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>Email address</li>
          </ul>

          <h3>Usage Data</h3>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type,
            browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages,
            unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including,
            but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device,
            Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h3>Fraud Prevention Data</h3>
          <p>To ensure fair use of our referral system and prevent abuse, we automatically collect:</p>
          <ul>
            <li><strong>IP address</strong> - Your network address when accessing the service</li>
            <li><strong>Device ID</strong> - A unique identifier stored in your browser's local storage</li>
            <li><strong>Device fingerprint</strong> - Technical information about your hardware (GPU model, CPU cores, screen resolution, media devices)</li>
            <li><strong>Browser fingerprint</strong> - Information about your browser configuration (canvas rendering, installed fonts, WebGL capabilities, audio rendering, timezone, language settings)</li>
          </ul>

          <div className="choice-option">
            <h3>Why We Collect Fraud Prevention Data</h3>
            <p>
              This data is collected solely for fraud prevention purposes using industry-standard techniques employed by
              major companies like Stripe, PayPal, Amazon, and Google. It helps us prevent:
            </p>
            <ul>
              <li>Self-clicking (users clicking their own referral links)</li>
              <li>VPN abuse (switching IP addresses to generate fake clicks)</li>
              <li>Bot attacks and automated click generation</li>
              <li>Duplicate claims (same device clicking multiple times)</li>
            </ul>
            <p>
              All fraud prevention data is <strong>hashed using SHA-256</strong> (irreversible) and <strong>automatically
              deleted after 24 hours</strong>.
            </p>
          </div>
        </section>

        <section className="policy-section">
          <h2>Tracking Technologies and Cookies</h2>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
            Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>

          <h3>Types of Cookies We Use</h3>

          <div className="cookie-type">
            <h3>Necessary / Essential Cookies</h3>
            <p><strong>Type:</strong> Session Cookies</p>
            <p><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided.</p>
          </div>

          <div className="cookie-type">
            <h3>Functionality Cookies</h3>
            <p><strong>Type:</strong> Persistent Cookies (localStorage)</p>
            <p><strong>Purpose:</strong> These allow us to remember choices You make when You use the Website, such as remembering your login details. The purpose is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
          </div>

          <p>For more information about the cookies we use, please visit our <a href="/cookie-policy">Cookie Policy</a>.</p>
        </section>

        <section className="policy-section">
          <h2>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain our Service</strong> including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the referral program and prize redemption.</li>
            <li><strong>To contact You:</strong> To contact You by email regarding updates or informative communications related to the Service, including security updates.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>Fraud prevention:</strong> To detect and prevent abuse, fraud, and manipulation of the referral system.</li>
            <li><strong>For other purposes:</strong> We may use Your information for data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>Sharing Your Personal Data</h2>
          <p>We may share Your personal information in the following situations:</p>
          <ul>
            <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service (e.g., Google Cloud Platform, Redis Labs).</li>
            <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
          </ul>
          <p><strong>We will not sell or monetize Your personal data to third parties.</strong></p>
        </section>

        <section className="policy-section">
          <h2>Retention of Your Personal Data</h2>
          <ul>
            <li><strong>Account data (email):</strong> Retained while your account is active. You may request deletion at any time.</li>
            <li><strong>Fraud prevention data:</strong> Automatically deleted after 24 hours.</li>
            <li><strong>Usage Data:</strong> Generally retained for a shorter period of time, except when used to strengthen security or improve functionality.</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>Transfer of Your Personal Data</h2>
          <p>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places
            where the parties involved in the processing are located.
          </p>
          <p>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance
            with this Privacy Policy. All data is stored within the UK and European Economic Area (EEA).
          </p>
        </section>

        <section className="policy-section">
          <h2>Security of Your Personal Data</h2>
          <p>The security of Your Personal Data is important to Us. We implement industry-standard security measures including:</p>
          <ul>
            <li><strong>Encryption:</strong> All data transmitted over HTTPS (SSL/TLS encryption)</li>
            <li><strong>Hashing:</strong> Passwords hashed using bcrypt; fingerprints hashed using SHA-256</li>
            <li><strong>Secure cookies:</strong> HttpOnly, Secure, and SameSite flags enabled</li>
            <li><strong>Access control:</strong> Limited access to personal data</li>
            <li><strong>Auto-deletion:</strong> Fraud detection data expires after 24 hours</li>
          </ul>
          <p>
            However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.
            While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>
        </section>

        <section className="policy-section">
          <h2>Your Rights Under UK GDPR</h2>
          <p>You have the following rights:</p>
          <ul>
            <li><strong>Right to access:</strong> Request copies of your personal data</li>
            <li><strong>Right to rectification:</strong> Correct inaccurate or incomplete data</li>
            <li><strong>Right to erasure:</strong> Request deletion of your data</li>
            <li><strong>Right to restrict processing:</strong> Limit how we use your data</li>
            <li><strong>Right to data portability:</strong> Receive your data in a machine-readable format</li>
            <li><strong>Right to object:</strong> Object to processing based on legitimate interests</li>
          </ul>
          <p>To exercise any of your rights, please contact us at: <strong>contact@flightstory.com</strong></p>
        </section>

        <section className="policy-section">
          <h2>Children's Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable
            information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child
            has provided Us with Personal Data, please contact Us.
          </p>
        </section>

        <section className="policy-section">
          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link,
            You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>
        </section>

        <section className="policy-section">
          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy
            Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are
            effective when they are posted on this page.
          </p>
        </section>

        <div className="contact-info">
          <p><strong>FLIGHTSTORY</strong></p>
          <p>73 Cornhill, London, EC3V 3QQ</p>
          <p>United Kingdom</p>
          <p>Email: contact@flightstory.com</p>
        </div>

        <div className="policy-footer">
          <p>
            If you have any questions about this Privacy Policy, You can contact us by email at: <strong>contact@flightstory.com</strong>
          </p>
          <div className="policy-links">
            <a href="/">← Back to Home</a>
            <a href="/terms-conditions">Terms & Conditions</a>
            <a href="/cookie-policy">Cookie Policy</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
